### ISSUE TITLE
Dragging a program over itself (moving it) has no highlight when the program has block id > 0

### ISSUE THREAD

**Issue by marekdedic** [janzarsky/scout-planner#244] opened 2023-05-16 13:07 UTC
When trying to move for example a 60' long program 15' later, there is a highlight in the place the program would be moved into. However, when the program has a "block id" greater than 0, the highlight is missing and is only shown when the new position wouldn't overlap with the original one.

**Comment by janzarsky** [comment] 2023-05-16 16:13
I cannot reproduce it, can you please check again? I did change this recently
![image](https://github.com/janzarsky/scout-planner/assets/748663/e679ddfb-a687-4091-8f43-fca891d21621)

**Comment by marekdedic** [comment] 2023-05-16 17:05
Oh, I only had 1 program. But playing with it more, it looks like the "drop area" is there, but is just significantly smaller in the place where the program originally was - see the difference when dragging a program that was originally at 12:

![image](https://github.com/janzarsky/scout-planner/assets/3134692/d0680a4d-6607-473a-bda2-9f7221d30b6d)

![image](https://github.com/janzarsky/scout-planner/assets/3134692/32e7b152-a800-4c2f-bc72-4b02d33375ee)

**Comment by janzarsky** [comment] 2023-06-03 19:54
this looks like something that only happens when the program has block order other than 0. I fixed one bug that might be related (#272), please retest

**Comment by janzarsky** [comment] 2023-06-03 19:55
solved by #272

**Closed by janzarsky** 2023-06-03 19:55 UTC
Labels: bug, question
